### ISSUE TITLE
需要帮助  err: TypeError: Cannot read property 'bind' of undefined

### ISSUE THREAD

**Issue by TYblog** [YunYouJun/hexo-tag-common#1]
```node
$ hexo clean
ERROR {
  err: TypeError: Cannot read property 'bind' of undefined
      at G:\newblog（OLD）\node_modules\hexo-tag-common\index.js:2:50
      at G:\newblog（OLD）\node_modules\hexo\lib\hexo\index.js:315:14
      at tryCatcher (G:\newblog（OLD）\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (G:\newblog（OLD）\node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (G:\newblog（OLD）\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (G:\newblog（OLD）\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (G:\newblog（OLD）\node_modules\bluebird\js\release\promise.js:729:18)
      at _drainQueueStep (G:\newblog（OLD）\node_modules\bluebird\js\release\async.js:93:12)
      at _drainQueue (G:\newblog（OLD）\node_modules\bluebird\js\release\async.js:86:9)
      at Async._drainQueues (G:\newblog（OLD）\node_modules\bluebird\js\release\async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (G:\newblog（OLD）\node_modules\bluebird\js\release\async.js:15:14)
      at processImmediate (internal/timers.js:456:21)
} Plugin load failed: %s hexo-tag-common
```
我需要帮助。

**Comment by YunYouJun** [comment]
请尝试使用 Node.js LTS(12.19.0) 与 Hexo v5.2.0。

**Comment by TYblog** [comment]
已解决。
方案：本地运行  `npm update` 主动升级到 hexo: 5.2.0。重新部署解决问题。附更新后`hexo v`运行结果:
```node
$ hexo v
INFO  Validating config
INFO  Yun version 1.2.0. Guide: https://yun.yunyoujun.cn
hexo: 5.2.0
hexo-cli: 4.2.0
os: Windows_NT 10.0.18363 win32 x64
node: 12.18.3
v8: 7.8.279.23-node.39
uv: 1.38.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.16.0
modules: 72
nghttp2: 1.41.0
napi: 6
llhttp: 2.0.4
http_parser: 2.9.3
openssl: 1.1.1g
cldr: 37.0
icu: 67.1
tz: 2019c
unicode: 13.0
```
结论：`hexo-tag-common`插件不支持 `hexo` 老版本，建议及时更新。
